### ISSUE TITLE
api.threats.api.specification.violation is not supported by this tool

### ISSUE THREAD

**Issue by mihaiturcu** [imperva/site-protection-viewer#1]
Hi,

I'm running with the following setup:
node -v 
v10.16.3

Apparently I'm receiving the following:
Check Origin Servers - total time: 60368.313ms
Get Site Info time: 60377.488ms
api.threats.api.specification.violation is not supported by this tool
/home/mihait/git/site-protection-viewer/utils.js:40
  for (var i = 0; i < policy.value.length; i++)
                             ^

TypeError: Cannot read property 'value' of undefined
    at Object.isProtected (/home/mihait/git/site-protection-viewer/utils.js:40:30)
    at buildPolicyReport (/home/mihait/git/site-protection-viewer/spv.js:804:27)
    at buildHtml (/home/mihait/git/site-protection-viewer/spv.js:440:21)
    at done (/home/mihait/git/site-protection-viewer/spv.js:231:7)
    at /home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:3888:9
    at /home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:1064:13)
    at /home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:969:16
    at /home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:3885:13
    at /home/mihait/git/site-protection-viewer/checkOriginReached.js:32:3
    at /home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:1064:13)
    at /home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:969:16
    at /home/mihait/git/site-protection-viewer/checkOriginReached.js:48:3
    at /home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:1064:13)
    at /home/mihait/git/site-protection-viewer/node_modules/async/dist/async.js:969:16
    at Request._callback (/home/mihait/git/site-protection-viewer/checkOriginReached.js:87:3)
    at self.callback (/home/mihait/git/site-protection-viewer/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/home/mihait/git/site-protection-viewer/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:198:13)

I'm running in debug mode. Could anyone guide me if I need a specific NodeJS version or something else?

Thanks,
Mihai

**Comment by dtzur1** [comment]
Please check new version 1.7.
Let me know if this issue was fixed.

**Comment by dtzur1** [comment]
As there was no further correspondance I assume all is well.
